version: '3.8'

services: 
  tour-app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - tour-network
    environment:
      - ENV=production
    depends_on:
      - db
    volumes:
      - ./config:/app/config

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tourdb
    networks:
      - tour-network
    volumes:
      - db-data:/var/lib/postgresql/data

  # Grafana for dashboards
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    networks:
      - tour-network
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - db
      - loki

  # Loki for log aggregation
  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    networks:
      - tour-network
    volumes:
      - loki-data:/loki

  # Promtail to ship logs to Loki
  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
      - ./promtail/config.yml:/etc/promtail/config.yml
    networks:
      - tour-network
    depends_on:
      - loki

  # NGINX as a reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - tour-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - tour-app
      - grafana

networks:
  tour-network:

volumes:
  db-data:
  grafana-data:
  loki-data:
